-- Desabilitar RLS (Row Level Security) em todas as tabelas
-- Execute este SQL no SQL Editor do Supabase

-- Tabelas principais (usando nomes corretos do schema)
ALTER TABLE "users" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "stores" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "products" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "product_variants" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "sales" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "sale_items" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "suppliers" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "cart_items" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "favorites" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "product_reviews" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "product_compatibility" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "color_analyses" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "furniture_analyses" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "comparisons" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "moodboards" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "moodboard_items" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "collections" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "chat_sessions" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "chat_messages" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "system_logs" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "daily_cash" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "cash_flows" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "cash_expenses" DISABLE ROW LEVEL SECURITY;

-- Verificar status do RLS
SELECT schemaname, tablename, rowsecurity 
FROM pg_tables 
WHERE schemaname = 'public' 
ORDER BY tablename;

